---

topic:
title:
instructors: []
instructor_emails: []
helpers: []
# A list of hh|mm time formats [avoids jekyll auto-conversion].
# Only days with scheduled items get a start time.
# Days which can't be matched will use the first entry.
start_times: ["09|00"]
# list of files in _includes/install_instructions to use in the setup page
setup_files: []
language: en
venue:
address:
country:
latitude:
longitude:
start_date:
collaborative_notes:
eventbrite:
# list of files in path _includes/intro/* .md files can be customised; .html files cannot be customised. Files with an initial _ are ignored.
optional_intro_sections: ["requirements", "accessibility"]

# Custom but fixed fields
kind: workshop
ukrn_email: ORT@ukrn.org
ukrn_site: https://ukrn.org/
repository: <USERNAME>/<PROJECT>
carpentries_site: https://carpentries.org/
pre_survey: https://carpentries.typeform.com/to/wi32rS?slug=
post_survey: https://carpentries.typeform.com/to/UgVdRQ?slug=

# Fixed fields
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  episodes_rmd:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

exclude:
  - Makefile
  - bin/
  - .Rproj.user/
highlighter: rouge

# UKRN Workshop Builder metadata
# Describes each of the custom variables
ukrn_wb:
    # We include the fields structure so that we can access JSON conversion of fields more readily (to numerical array where keys correspond to this numerical array).
    # This does mean that all properties are required for all fields
  - fields_structure:
      - name # Pretty name of the field
      - type # Data type
      - help # Help text
      - is_array # Whether data is a list
      - is_required # Whether field is required
      - format # Formatting details for data
      - special # Special information for deriving data e.g. options list
  - fields:
      - topic:
          - Workshop topic
          - string
          - >-
            The topic is used to search for pre-existing lessons you can include in your workshop
          - false
          - true
          - topic
          - # special
      - title:
          - Workshop title
          - string
          - >-
            The title should let people know the most important information - where the workshop is and what it covers
          - false
          - true
          - # format
          - # special
      - instructors:
            - Workshop instructor(s)
            - string
            - >-
                Instructor name(s)
            - true # is_array
            - true # is_required
            - # format
            - # special

      - instructor_emails:
            - Contact email address(es)
            - string
            - >-
                Instructor email address(es) for questions/comments/feedback
            - true # is_array
            - # is_required
            - email # format
            - # special
      - helpers:
            - Workshop helper(s)
            - string
            - >-
                Helper name(s)
            - true # is_array
            - # is_required
            - # format
            - # special
      - start_times:
          - Start time
          - time
          # The time is actually converted to 09_00 format
          - >-
            Start times (in 0900 format) for each day of the workshop. If shorter than the number of days, remaining days will use the first entry
          - true
          - true
          - hours_minutes
          - # special

      - setup_files:
            - Setup instructions
            - filename
            - >-
                List of setup guides to include on the homepage
            - true # is_array
            - # is_required
            - # format
            - ["_includes/install_instructions"] # special - directories to search

      - language:
            - Workshop language
            - string
            - >-
                Language code for the language the workshop will be conducted in
            - # is_array
            - # is_required
            - iso-639-1
            - # special

      - venue:
          - Workshop venue
          - string
          - >-
            The brief name of the institution that hosts the workshop without address (e.g., "Euphoric State University")
          - # is_array
          - # is_required
          - # format
          - # special
      - address:
          - Venue address
          - string
          - >-
            The full street address of workshop (e.g., "Room A, 123 Forth Street, Blimingen, Euphoria"), videoconferencing URL, or 'online'
          - # is_array
          - # is_required
          - long # format
          - # special
      - country:
          - Workshop country
          - string
          - >-
            Country code for the institution that hosts the workshop
          - # is_array
          - # is_required
          - iso-3166-1-alpha-2
          - # special
      - latitude:
            - Workshop latitude
            - number
            - >-
                Latitude of workshop venue (use <a href="https://www.latlong.net/">https://www.latlong.net"</a>)
            - # is_array
            - # is_required
            - latitude
            - # special
      - longitude:
            - Workshop longitude
            - number
            - >-
                Longitude of workshop venue (use <a href="https://www.latlong.net/">https://www.latlong.net"</a>)
            - # is_array
            - # is_required
            - longitude
            - # special

      - start_date:
            - Workshop start date
            - date
            - >-
                Date the workshop starts.
            - # is_array
            - # is_required
            - years-months-days
            - # special

      - collaborative_notes:
          - Collaborative notes link
          - string
          - >-
            URL for the workshop collaborative notes, e.g. an Etherpad or Google Docs document
          - # is_array
          - # is_required
          - # format
          - # special
      - eventbrite:
          - Eventbrite key
          - string
          - >-
            The alphanumeric key for Eventbrite registration, e.g., "1234567890AB"
          - # is_array
          - # is_required
          - # format
          - # special
      - optional_intro_sections:
          - Optional introductory sections
          - filename
          - >-
            Optional introductory sections which can be included on the homepage and customised
          - true # is_array
          - # is_required
          - # format
          - ["_includes/intro"] # special - directories to search
